spring.application.name=donaciones
server.port=8082

# === CONEXIÓN A RENDER ===
spring.datasource.url=jdbc:postgresql://dpg-d7qkl6sm0tmc73fn8mdg-a.oregon-postgres.render.com:5432/donaton_db?sslmode=require
spring.datasource.username=donaton_db_user
spring.datasource.password=s2yhWU4UbqQS9eP5nWryLPcDoKEloa1d
spring.datasource.driver-class-name=org.postgresql.Driver

# === JPA / HIBERNATE ===
spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true

# Schema por defecto (uno de los 3 que creaste)
spring.jpa.properties.hibernate.default_schema=necesidades

logging.level.org.hibernate.SQL=DEBUG
logging.level.org.hibernate.type.descriptor.sql.BasicBinder=TRACE